# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-26 00:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='description',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='show',
            name='network',
            field=models.CharField(max_length=45),
        ),
    ]
